version: '3.9'
services:
  db:
    image: postgres
    container_name: gestao_vagas_postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: gestao_vagas
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    ports:
      - 5433:5432
    networks:
      - dev-network

  sonarqube:
    image: sonarqube:9.9.0-community
    container_name: sonarqube
    ports:
      - 9000:9000
    networks:
      - dev-network
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    depends_on:
      - db

networks:
  dev-network:
    driver: bridge

volumes:
  postgres-volume:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: 'D:\docker\novoVolume'
