version: '3.8'

services:
  postgres:
    container_name: gestao_vagas_db
    image: postgres
    ports:
      - 5423:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=gestao_vagas



